### ISSUE TITLE
Aliases, which include "scope:source.json" context, reset advanced JSON syntax to default "JavaScript -> JSON" 

### ISSUE THREAD

**Issue by serhiipalash** [SublimeText/AFileIcon#14]
#### Expected Behavior

AFileIcon's syntaxes `source.json.babel`, `source.json.bower`, `source.json.npm`, etc., should include theme advanced JSON syntax and not default Sublime "JavaScript -> JSON" syntax.

#### Current Behavior

Each AFileIcon custom JSON syntax uses default Sublime syntax for JSON-files, and it is not possible to select an advanced syntax (next time you open a file, it uses again "JavaScript -> JSON").

When you open regular JSON-file (not `package.json` or `.babelrc`) everything looks fine because it doesn't have a custom icon described in `AFileIcon` custom syntax.

https://drive.google.com/file/d/1gN0C-HRJ9W4VqAvYQeE9CPlIhqgljg6I/view

https://drive.google.com/file/d/1ELfW6y01a_XCSXsa5kVIPF4rujPMTX9v/view

With `.js` files everything looks fine even when `gulpfile.js` file is opened with custom `AFileIcon` syntax `JavaScript (Gulpfile)`.

#### Possible Solution

I am not sure if it is a bug in `AFileIcon` package or in Sublime itself. I tried to change different aliases configs, but nothing works.

#### Steps to Reproduce (for bugs)

1. Install `Babel` package
2. Install `Oceanic Next` theme and select it as Sublime theme
3. Create and open `package.json` file
4. Set syntax for all JSON-files to `Babel -> JSON`
5. Close `package.json`
6. Open it again

You will see that the syntax is not a `Babel -> JSON`, but it is a `JavaScript -> JSON`

#### Your Environment

OS: Mac OS
<img width="318" alt="Screen Shot 2019-07-08 at 5 44 14 PM" src="https://user-images.githubusercontent.com/14208343/60819459-483c4d80-a1a8-11e9-84ae-003bbfb50a64.png">

**Comment by deathaxe** [comment]
The issue is caused by Babel's JSON syntax, which just defines a plain `source.json` scope, which ST has already assingned to its builtin JSON syntax. As scopes are the main key to identify file types, assign icons and decide which syntax to apply, ST just doesn't know which one to pickup. It just uses the first one it finds, which is the builtin one due to loading order.

Babel would need to specify a unique scope like `source.json.babel`. This would then enable it to be assigned a file extension and unique icon to.

**Working Best Practise Example**

The same thing works pretty fine for any `sublime-...` file type. ST assigns `source.yaml` or `source.json`. A File Icon overloads these scopes by `source.yaml.sublime` and `source.json.sublime` with an alias syntax to be able to assign a unique icon. PackageDev package assigns the same and/or more specific scopes for these types, like `source.yaml.sublime.syntax`, which makes A File Icon provide the icon and PackageDev the syntax definition.

**Workaround**

If the Babel author doesn't intend to change the main scope you could define your own alias and make sure to place it in front of the _Packages/zzz A File Icon zzz_ package's loading order

```
%YAML 1.2
---
name: JSON (Babel)
file_extensions:
  - json
scope: source.json.babel

contexts:
  main:
    - include: Packages/Babel/JSON.tmLanguage
```

But I don't find a reason why one would use such an old JSON definition. The builtin one is pretty perfect so far. The only issue might be the new standardized `meta.mapping.key`, `meta.mapping.value` scopes not to be defined in most color schemes, which makes ST highlight everything as `string` only.

**Comment by serhiipalash** [comment]
@deathaxe thank you for your answer!
Yes, I was about to write that the problem is that `meta.mapping.key` and `meta.mapping.value` are not a part of my theme. I guess the only way to fix it is to update the theme, what do you think?

**Comment by serhiipalash** [comment]
> As scopes are the main key to identify file types, assign icons and decide which syntax to apply, ST just doesn't know which one to pickup. It just uses the first one it finds, which is the builtin one due to loading order.

> But I don't find a reason why one would use such an old JSON definition. The builtin one is pretty perfect so far. The only issue might be the new standardized `meta.mapping.key`, `meta.mapping.value` scopes not to be defined in most color schemes, which makes ST highlight everything as `string` only.

There is the same problem with `AFileIcon` aliases for JS-files, like `gulpfile.js`. The syntax in such files uses default ST `JavaScript` syntax and this problem can't be fixed with updating names in theme as `Babel -> JavaScripts` adds new names in syntax and not only rename existing.

Do you think is it possible to make ST pick `Babel -> JavaScript ` before default `JavaScript`? I think ST should pick syntax for `source.js` based on selected syntax for all JS-files and not based on which is default one. Changing the `scope` to `source.js.babel` in `Babel -> JavaScript` syntax may stop other packages to work with JS-files if they relay on `scope` value.

**Comment by serhiipalash** [comment]
Disabling default `JavaScript` syntax package solves all problems even if it is a hack. Closing this issue.

**Comment by deathaxe** [comment]
> update the theme, what do you think?

It's a pitty to see most color schemes to no longer be maintained. So if you have a favourite one, it might be worth putting the effort into it. Maybe you can handle it without much effort by looking for the old `meta.structure` and `meta.list` selectors. After doing some theming, I must confess it to be a quite sophisticated task.

> Disabling default JavaScript syntax 

Maybe the best solution, then. Even though one can assign file extensions to a specific sublime-syntax via a syntax specific sublime-settings file, the icons would still be applied by scope only and therefore not change.

**Comment by JustinShift** [comment]
Anybody else that comes across this issue, my understanding is that AFileIcon is coming up as it starts with `A`, but its has nothing to do with AFileIcon.

**The fix for me (but I cant explain it) was to:**

1. Disable the **JavaScript** plugin
1. Close & Re-open Sublime
1. Enable the **JavaScript** plugin
1. Close and Re-open Sublime

No more error, working as expected.

I suspect I will need to do this when package update in the future.
