### ISSUE TITLE
[Question] Is there a way to force a certain icon theme?

### ISSUE THREAD

**Issue by kud** [SublimeText/AFileIcon#23]
My theme (meetio) has its own icons but I'd like to have another theme for the icons. Is there a setting to force another theme?

Thank you.

**Comment by deathaxe** [comment]
Unfortunatelly there is no direct setting to switch between different icon sets. Sublime Text looks for icons only in the same directory or in an _icons_ sub directory which is located right next to the sublime-theme file.

Due to ST's way to handle its "virtual filesystem" for resources internally, the following would work though. The way to go was to dynamically create an empty dummy sublime-theme file in the folder which contains the desired iconset . 

**Structure with loosen theme package**

```
+-Packages
  |
  +-Meetio
    |
    +-iconsets
    | |
    | +-iconset1
    | | |
    | | +-file_type_default.png
    | | +-Meetio.sublime-theme      ; dynamically created empty theme to activate iconset1
    | |
    | +-iconset2
    | | |
    | | +-file_type_default.png
    |   
    +-Meetio.sublime-theme          ; the real theme with all rules
```


**Structure with packed theme package**

```
+-Installed Packages
| |
| +-Meetio.sublime-package
|   |
|   +-iconsets
|   | |
|   | +-iconset1
|   | | |
|   | | +-file_type_default.png
|   | |
|   | +-iconset2
|   | | |
|   | | +-file_type_default.png
|   |   
|   +-Meetio.sublime-theme          ; the real theme with all rules
|
+-Packages
  |
  +-Meetio
    |
    +-iconsets
      |
      +-iconset1
        |
        +-Meetio.sublime-theme      ; dynamically created empty theme to activate iconset1
```

Please note, that ST 4xxx still suffers from https://github.com/sublimehq/sublime_text/issues/3057 which may prevent it from correctly reloading new icons without restarting.

**Comment by kud** [comment]
Thank you very much for this clear explanation @deathaxe !
