### ISSUE TITLE
zzz A File Icon zzz displayed in the remove packages section

### ISSUE THREAD

**Issue by stephen147** [SublimeText/AFileIcon#45]
Thanks vey much for these

**ST build 3211 - Fresh install
Microsoft Windows 10 Pro (Build 19042)**

If I go to the remove packages `zzz A File Icon zzz` is displayed. The `A File Icon` is at the top which I'd expect. 

Just curious, should that be there in that list?

![image](https://user-images.githubusercontent.com/14054664/114289139-6d40ad00-9a6d-11eb-8f0b-f1f0700fb016.png)

**Comment by deathaxe** [comment]
The `zzz A File Icon zzz` folder is created dynamically to make sure it loads after all other packages. Otherwise themes might overwrite single icons.

This folder is removed by A File Icon automatically if the package is disabled or uninstalled.

A File Icon however has no chance to hide it from Package Control's quick panels at the moment.

You can ignore this folder.

Uninstalling temporarily breaks all icons. The folder is re created during the next application startup then.

**Comment by stephen147** [comment]
Thanks for the explanation. I just wondered what that was.
