### ISSUE TITLE
Different icon for hpp?

### ISSUE THREAD

**Issue by ellipticaldoor** [SublimeText/AFileIcon#51]
It will be nice if the color of the .hpp icon was different from the .cpp one

![image](https://user-images.githubusercontent.com/3449006/120934624-ffc09e00-c6f6-11eb-9411-5bd3df0c6a4f.png)

**Comment by ellipticaldoor** [comment]
Seems like the plugin decides the icon by its language association and not the extension.

**Comment by deathaxe** [comment]
This is how icons are assigned by ST. It needs a dedicated scope (language). Each variant therefore needs its own syntax definition file.

**Comment by deathaxe** [comment]
Added in 3.17.0

**Comment by LinuxDevon** [comment]
Looks like my file icons are completely gone for `hpp` file. I am updated to `v3.17.0`. Not sure if something needs refreshed or what but gave Sublime a restart and no dice.

**Comment by deathaxe** [comment]
A File Icon names c++ headers `file_type_cppheader`. Do you have any 3rd-party themes installed? Some of them are known to ship own icons for certain file types. If such a theme defines another name (e.g.: `file_type_hpp` or something along those lines, it can cause this kind of issue.

Note: It's enough to have such a theme installed. It doesn't need to be selected.

Otherwise A File Icons resets all caches during upgrade. So any new icon should be available immediately. If in doupt you could try to reset it manually via `Main Menu > Preferences > Package Settings > A File Icon > Revert to freshly installed state`

**Comment by LinuxDevon** [comment]
Sweet the reset manually seemed to fix it. Just realized that the `.h` files are included and still show up as `c++` icon. That is probably a separate issue though.

**Comment by deathaxe** [comment]
`.h` files are assigned to C++ icon by design. I don't plan to provide separate icons as .h files are historically used in many c++ projects. Thus they can't be distinguished reliably.

ST's C++ syntax is assigned to .h files by default as well.

**Comment by LinuxDevon** [comment]
Yea that makes sense as for distinguishing between C/C++. I was saying though that a `X.h` shows up with the original icon shown in: https://github.com/SublimeText/AFileIcon/issues/51#issue-912901801. It doesn't show the new `H` icon.

**Comment by LinuxDevon** [comment]
Forgot to come back to this and update. I didn't see any `Always Open with...` files nor the `C++.sublime-settings` file.

**Comment by deathaxe** [comment]
To check assigned syntax ...

1. open a hpp file
2. run following command from ST's console

The result should be

```
>>> view.syntax()
Syntax('Packages/zzz A File Icon zzz/aliases/C++ (Header).sublime-syntax', 'C++ (Header)', True, 'source.c++.header')
```

**Comment by LinuxDevon** [comment]
Run one was with a `.hpp` open and run two was with a `.h`
```txt
>>> view.syntax()
Syntax('Packages/zzz A File Icon zzz/aliases/C++ (Header).sublime-syntax', 'C++ (Header)', True, 'source.c++.header')
>>> view.syntax()
Syntax('Packages/C++/C++.sublime-syntax', 'C++', False, 'source.c++')
```
