### ISSUE TITLE
Unable to apply user preferences

### ISSUE THREAD

**Issue by TheFoolishPupil** [SublimeText/AFileIcon#54]
I'm trying to apply user settings for the package as per the documentation via `Preferences → Package Settings → A File Icon → Settings`. I try to change the icon size with the following sublime-settings file:
```json
// A File Icon Preferences – User
// ================================================================
{
	"size": 4
}
```
The change does not take effect and there is a pop up with the message `Error loading syntax file "Packages/zzz A File Icon zzz/aliases/JSON (Sublime).sublime-syntax": Unable to read Packages/zzz A File Icon zzz/aliases/JSON (Sublime).sublime-syntax`

#### Expected Behavior
I expect that the icon size changes.

#### Current Behavior
There is no change and there is a pop up with an error message.

#### Environment
I can't seem to find the environment command via the command palette, nor the settings menu. 
I am on MacOS Big Sur, and Sublime Text build 4113
output from the console:
```
reloading settings Packages/User/A File Icon.sublime-settings
ignored packages updated to: ["Vintage", "zzz A File Icon zzz"]
reloading settings Packages/User/Preferences.sublime-settings
error: Error loading syntax file "Packages/zzz A File Icon zzz/aliases/JSON (Sublime).sublime-syntax": Unable to read Packages/zzz A File Icon zzz/aliases/JSON (Sublime).sublime-syntax
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by deathaxe** [comment]
The setting is meant to tweak icon appeareance of themes, which are not known to support A File Icon, such as Default/Adaptive.

A File Icon only applies least required patch to themes which claim to support A File Icon, such as AYU and Theme - DAneo. The "size" is not part of it, atm.

The error message `Error loading syntax file ...` is caused by the mensioned syntax being removed and recreated once A File Icon settings change while a view with such a syntax is still open (the settings).

Enabling/Disabling aliases is already handled so it should be possible to avoid it in this situation as well.

**Comment by TheFoolishPupil** [comment]
Ah okay thanks @deathaxe. I am indeed using Ayu theme together with A File Icon. If I understand correctly then, there isn't an ability to change the size of the icons provided by A File Icon?

**Comment by deathaxe** [comment]
Not at the moment, no. It shouldn't be a big deal to change that though.

**Comment by itcgq** [comment]
Preferences → Package Settings → A File Icon → Settings  ，An error：The settings file "res://Packages/A File Icon/.sublime/A File Icon.sublime-settings" could not be opened

**Comment by deathaxe** [comment]
This error message can be ignored. It's a false positive unrelated with this issue.
